[package]
authors = ["Pouya M. B. <pooyamb@gmail.com>"]
name = "json-resp-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.39"
quote = "1.0.18"
syn = "1.0.96"

[features]
openapi = []
log = []
